//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Application_Using_Ajax_GridView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender_detail
    {
        public int Gender_Id { get; set; }
        public string Info { get; set; }
    }
}
